default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Using environment variables from GitHub secrets for authentication
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      in_house: false
    )
    # Sync provisioning profiles using Fastlane Match
    match(type: "development")  # This will sync development profiles
    # Increment the build number
    increment_build_number(xcodeproj: "Runner.xcodeproj")

    # Use xcodebuild to build the app with the -allowProvisioningUpdates flag
    sh "xcodebuild -workspace Runner.xcworkspace -scheme Runner -destination 'generic/platform=iOS' -archivePath '~/Library/Developer/Xcode/Archives/Runner.xcarchive' archive -allowProvisioningUpdates"

    # Build the app using Fastlane's build_app
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")

    # Upload the build to TestFlight
    upload_to_testflight(api_key: api_key)
  end
end
