name: TestFlight Deployment

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
           ruby-version: '3.0'  # Specify the Ruby version compatible with Fastlane

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up fastlane environment
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          bundle exec fastlane beta  # Run the Fastlane lane to upload to TestFlight
