name: TestFlight Deployment

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      # Debugging: List the directory structure
      - name: List current directory structure
        run: pwd  # Print the current working directory

      # - name: List the contents of the ios_deployment_demo directory
      #   run: ls -R ios_deployment_demo  # List the directory structure inside ios_deployment_demo

      - name: List the contents of the ios directory
        run: ls -R ./ios  # List the directory structure of the ios folder

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
           ruby-version: '3.0'  # Specify the Ruby version compatible with Fastlane

      - name: Install dependencies
        working-directory: ./ios

        run: |
          gem install bundler
          bundle install

      - name: Set up fastlane environment
        working-directory: ./ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          bundle exec fastlane beta  # Run the Fastlane lane to upload to TestFlight
